qBraid/qbraid-qir

- examples/rigetti_qvm_sim.ipynb
*issue tag(s), if exist*: #28 
- Added examples folder
- Added example running compiled QIR code on Rigetti QVM simulator via azure quantum cloud
> azure + rigetti example notebook

- .github/workflows/main.yml
- pyproject.toml
- qbraid_qir/cirq/elements.py
- qbraid_qir/cirq/passes.py
- qbraid_qir/cirq/visitor.py
- qbraid_qir/serialization.py
- requirements-dev.txt
- tests/resources/test_conditional_gates.ll
- tests/test_cirq_to_qir.py
- tests/test_serialization.py
Improved Code coverage to somewhere around 98%
> improved code-cov

- qbraid_qir/qasm3/visitor.py
- tests/qasm3_qir/converter/test_barrier.py
- tests/qasm3_qir/converter/test_expressions.py
- tests/qasm3_qir/converter/test_gates.py
- tests/qasm3_qir/converter/test_if.py
- tests/qasm3_qir/converter/test_measurement.py
- tests/qasm3_qir/test_convert.py
- tests/qir_utils.py
Fixes #65  
- Add tests for different qasm3 files to bring coverage up to 95%
> Improve coverage for `qasm3` converter

- pyproject.toml
> bump qbraid dependency

- README.md
> Update README.md with qasm3 supported OPs

- README.md
- qbraid_qir/qasm3/README.md
> progress table template

- qbraid_qir/qasm3/README.md
Adding some unsupported instructions to `README`
> Update README.md for supported instrs

- .github/workflows/main.yml
- README.md
> update discord icon + add codecov

- pyproject.toml
- qbraid_qir/_version.py
> bump version

- qbraid_qir/qasm3/visitor.py
- tests/qasm3_qir/converter/declarations/test_quantum.py
- tests/qasm3_qir/fixtures/subroutines.py
- tests/qasm3_qir/fixtures/variables.py
Fixes #131 
- Add the quantum variables in the scope for re-declaration checks
> Fix the classical declaration bug 

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- CITATION.cff
- CONTRIBUTING.md
- README.md
- docs/index.rst
- qbraid_qir/_version.py
- update readme / citation for new version
- fixed some wording and links
- added changelog
- updated pr template + contributing doc
> housekeeping updates

- qbraid_qir/qasm3/transformer.py
- qbraid_qir/qasm3/visitor.py
- tests/qasm3_qir/converter/test_gates.py
Fixes #156 
- Added a transform method to recursively update the parameter values inside an expression of a gate parameter
> Add support for param update in gate param expr

- qbraid_qir/_version.py
- qbraid_qir/qasm3/__init__.py
- qbraid_qir/qasm3/analyzer.py
- qbraid_qir/qasm3/checker.py
- qbraid_qir/qasm3/elements.py
- qbraid_qir/qasm3/maps.py
- qbraid_qir/qasm3/subroutines.py
- qbraid_qir/qasm3/visitor.py
- tests/qasm3_qir/test_checker.py
- small tweaks of checker function
> update checker and bump version

- CHANGELOG.md
- CITATION.cff
- README.md
- qbraid_qir/_version.py
- update versions, reset changelog
> update versions,  reset changelog

- pyproject.toml
- qbraid_qir/qasm3/analyzer.py
- qbraid_qir/qasm3/elements.py
- qbraid_qir/qasm3/expressions.py
- qbraid_qir/qasm3/maps.py
- qbraid_qir/qasm3/subroutines.py
- qbraid_qir/qasm3/visitor.py
- tox.ini
Add expression evaluator as a parameter for method
> Fix cyclic import in analyser

- pyproject.toml
- qbraid_qir/__init__.py
- tests/qasm3_qir/test_linalg.py
- update lazy imports, add a few linalg tests
> update lazy imports, add linalg tests

- README.md
- docs/index.rst
- fix / update broken notebook examples links
> fix broken links

- pyproject.toml
> Bump the pyqasm version

- qbraid_qir/qasm3/README.md
Update `README.md` with new qasm support
> Update `README.md` with new qasm support

- CHANGELOG.md
- CITATION.cff
- README.md
- qbraid_qir/_version.py
* Updated version number to 0.3.0 and `CHANGELOG.md`
> Update changelog + version update

- README.md
> Fix license link 

- pyproject.toml
- Update license from GPL 3 to apache 2.0 in pyproject.toml
> Update license in pyproject.toml [no ci]

- .github/workflows/bump-version.yml
- .github/workflows/gh-pages.yml
- CHANGELOG.md
- CITATION.cff
- bin/bump_version.py
- bin/create_dev_build.sh
- bin/install_wheel_extras.sh
- bin/stamp_dev_version.sh
- bin/update_citation.py
- docs/_static/css/custom.css
- docs/index.rst
- Add deploy to github pages workflow
- Add version bump workflow
> gh pages + bump version workflows

- .github/dependabot.yml
- docker/linux-amd64/Dockerfile
- docker/linux-amd64/build.sh
- docker/linux-amd64/exec.sh
- docker/linux-amd64/run.sh
- Update docker module scripts to apache-2.0
> update docker scripts to apache-2.0

- .github/workflows/gh-pages.yml
- Deploy to gh pages only on published release
> Update gh-pages.yml [no ci]

- CHANGELOG.md
- pyproject.toml
Update pyqasm version to `>=0.3.2, < 0.4.0`
> Update pyqasm version to `>=0.3.2, < 0.4.0`

- CHANGELOG.md
- README.md
- reset changelog and update readme citation
> reset changelog and update citation [no ci]

- CHANGELOG.md
- pyproject.toml
Bump pyqasm version to `0.4.0`
> Bump pyqasm version to `0.4.0`

- CHANGELOG.md
- pyproject.toml
- Update `pyqasm` requirement from >=0.4.0,<0.5.0 to >=0.4.0,<0.6.0
> Update `pyqasm` requirement from >=0.4.0,<0.5.0 to >=0.4.0,<0.6.0
